%%{init: {"theme":"base","flowchart":{"nodeSpacing":35,"rankSpacing":45},"themeVariables":{
  "background":"#ffffff",
  "primaryColor":"#ffffff",
  "primaryTextColor":"#000000",
  "primaryBorderColor":"#000000",
  "lineColor":"#000000",
  "secondaryColor":"#ffffff",
  "tertiaryColor":"#ffffff",
  "fontFamily":"Arial",
  "fontSize":"14px",
  "nodePadding":18
}}}%%
flowchart LR
  C["Intensity to HU"] --> D["Orientation / Laterality Standardization"]
  D --> E["Rule-based Orbital ROI Cropping"]

  E --> F{"Task branch"}

  %% Fracture detection branches
  F -->|Fracture detection| G{"Plane"}
  G -->|Axial| H["Rule-based Selection of 40 Contiguous Slices"]
  G -->|Coronal| I["Rule-based Selection of 32 Contiguous Slices"]

  H --> J["Resize into 150x120"]
  I --> K["Resize 256x256"]

  %% Severity (SGI) branch
  F -->|Severity Estimation / SGI| L["Rule-based Selection of 40 Contiguous Slices in axial orientation"]
  L --> M["Resize into 150x120"]

  %% Common final steps
  J --> N["Min-max normalization"]
  K --> N
  M --> N
  N --> O["Save as .npy stacks"]

